### ISSUE TITLE
phpstan issue

### ISSUE THREAD

**Issue by dingo-d** [Zodiac1978/mail-on-update-reloaded#3]
Hi!

Try setting your `phpstan.neon` config to this:

```yml
includes:
  - vendor/phpstan/phpstan/conf/bleedingEdge.neon
  - vendor/szepeviktor/phpstan-wordpress/extension.neon
parameters:
  level: 5
  paths:
    - mail-on-update.php
```

This should fix the discovery of WordPress stubs.

As for CI, you can use the `phpstan-wp-action` action, or you can just do this:

```yml
    steps:
      - name: "Set up PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          coverage: none
          tools: phpstan

      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Install Composer dependencies"
        uses: "ramsey/composer-install@v2"
        with:
          custom-cache-suffix: $(date -u "+%Y-%m")

      - name: "Run PHPStan"
        run: phpstan analyse
```

That should achieve the same thing.
